In [2]:
# loading the data
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# checking with pure functions
def dataset_info(dataframe: pd.DataFrame) -> dict:
    return {
        "rows": dataframe.shape[0],
        "columns": dataframe.shape[1],
        "column_names": list(dataframe.columns)
    }
dataset_info(df)

{'rows': 150,
 'columns': 5,
 'column_names': ['sepal_length',
  'sepal_width',
  'petal_length',
  'petal_width',
  'species']}

In [4]:
# adding an invalid or bad data
df.loc[0, "species"] = ""

In [5]:
def remove_invalid_rows(dataframe: pd.DataFrame) -> pd.DataFrame:
    valid_indices = filter(lambda idx: dataframe.loc[idx, "species"].strip() != "", dataframe.index)
    cleaned_df = dataframe.loc[list(valid_indices)].reset_index(drop=True)
    return cleaned_df

# Cleaned version of the dataset
clean_df = remove_invalid_rows(df)
clean_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           4.9          3.0           1.4          0.2  setosa
1           4.7          3.2           1.3          0.2  setosa
2           4.6          3.1           1.5          0.2  setosa
3           5.0          3.6           1.4          0.2  setosa
4           5.4          3.9           1.7          0.4  setosa

In [6]:
def normalize_species(dataframe: pd.DataFrame) -> pd.DataFrame:
    df_copy = dataframe.copy()
    df_copy["species"] = df_copy["species"].map(lambda x: x.strip().title())
    return df_copy

normalized_df = normalize_species(clean_df)
normalized_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           4.9          3.0           1.4          0.2  Setosa
1           4.7          3.2           1.3          0.2  Setosa
2           4.6          3.1           1.5          0.2  Setosa
3           5.0          3.6           1.4          0.2  Setosa
4           5.4          3.9           1.7          0.4  Setosa

In [12]:
# functional 
length_list_fp = list(
    map(lambda x: x * 2, filter(lambda x: x > 5.0, df["sepal_length"]))
)

length_list_fp[:5]

[10.2, 10.8, 10.8, 11.6, 11.4]

In [8]:
# counting of each species 
from collections import Counter

species_counts = dict(Counter(normalized_df["species"].map(lambda x: x)))
species_counts

{'Setosa': 49, 'Versicolor': 50, 'Virginica': 50}

In [9]:
# now using group by average
grouped_avg = normalized_df.groupby("species")["sepal_length"].mean().to_dict()
grouped_avg

{'Setosa': 5.004081632653061,
 'Versicolor': 5.936,
 'Virginica': 6.587999999999999}